# Nama Project : Memprediksi Kualitas Susu (Low, Medium, High) Berdasarkan Dataset "milknew.csv" menggunakan Algoritma Naive Bayes

## Nama : Rifai Nugroho
## NIM : 10121295
## Kelas : IF8
## Jurusan : Teknik Informatika S1
## Asal Kampus : Universitas Komputer Indonesia (Kota Bandung)

In [ ]:
import numpy as np
import pandas as pd

from google.colab import files
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

## Silakan Upload File di Sini

In [ ]:
uploaded=files.upload()

Saving milknew.csv to milknew (1).csv


## Menampilkan Dataset

In [ ]:
dataset = pd.read_csv('milknew.csv')
dataset.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0  6.6          35      1     0     1          0     254    high
1  6.6          36      0     1     0          1     253    high
2  8.5          70      1     1     1          1     246     low
3  9.5          34      1     1     0          1     255     low
4  6.6          37      0     0     0          0     255  medium

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64  
 2   Taste       1059 non-null   int64  
 3   Odor        1059 non-null   int64  
 4   Fat         1059 non-null   int64  
 5   Turbidity   1059 non-null   int64  
 6   Colour      1059 non-null   int64  
 7   Grade       1059 non-null   object 
dtypes: float64(1), int64(6), object(1)
memory usage: 66.3+ KB


In [ ]:
dataset.empty

False

## Merubah Tipe Data Object ke Integer

In [ ]:
en = LabelEncoder()
dataset['Grade'] = en.fit_transform(dataset['Grade'])
dataset.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour  Grade
0  6.6          35      1     0     1          0     254      0
1  6.6          36      0     1     0          1     253      0
2  8.5          70      1     1     1          1     246      1
3  9.5          34      1     1     0          1     255      1
4  6.6          37      0     0     0          0     255      2

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64  
 2   Taste       1059 non-null   int64  
 3   Odor        1059 non-null   int64  
 4   Fat         1059 non-null   int64  
 5   Turbidity   1059 non-null   int64  
 6   Colour      1059 non-null   int64  
 7   Grade       1059 non-null   int64  
dtypes: float64(1), int64(7)
memory usage: 66.3 KB


In [ ]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
x

array([[  6.6,  35. ,   1. , ...,   1. ,   0. , 254. ],
       [  6.6,  36. ,   0. , ...,   0. ,   1. , 253. ],
       [  8.5,  70. ,   1. , ...,   1. ,   1. , 246. ],
       ...,
       [  3. ,  40. ,   1. , ...,   1. ,   1. , 255. ],
       [  6.8,  43. ,   1. , ...,   1. ,   0. , 250. ],
       [  8.6,  55. ,   0. , ...,   1. ,   1. , 255. ]])

In [ ]:
y

array([0, 0, 1, ..., 1, 0, 1])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))

x_train =  847
x_test =  212
y_train =  847
y_test =  212


In [ ]:
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_train

array([[ 0.1258701 , -0.41330182,  0.91504655, ...,  0.6803433 ,
        -0.99411413, -1.61267828],
       [-0.01505782,  0.09729713, -1.09284057, ..., -1.46984617,
         1.00592071, -0.43999756],
       [ 0.1258701 ,  0.09729713,  0.91504655, ...,  0.6803433 ,
        -0.99411413, -1.61267828],
       ...,
       [-0.08552179, -0.82178098, -1.09284057, ...,  0.6803433 ,
        -0.99411413,  0.73268316],
       [-0.01505782,  0.60789609, -1.09284057, ..., -1.46984617,
         1.00592071, -0.43999756],
       [ 0.1258701 ,  0.09729713,  0.91504655, ...,  0.6803433 ,
        -0.99411413, -1.61267828]])

In [ ]:
x_test

array([[-0.01505782, -0.41330182,  0.91504655, ...,  0.6803433 ,
         1.00592071,  0.73268316],
       [-1.49480102,  1.62909399, -1.09284057, ...,  0.6803433 ,
         1.00592071, -0.43999756],
       [ 1.67607726, -0.10694245,  0.91504655, ...,  0.6803433 ,
         1.00592071, -0.43999756],
       ...,
       [ 0.1258701 , -0.31118203, -1.09284057, ..., -1.46984617,
        -0.99411413,  0.73268316],
       [-0.08552179, -0.82178098, -1.09284057, ...,  0.6803433 ,
        -0.99411413,  0.26361087],
       [-0.01505782,  0.09729713, -1.09284057, ...,  0.6803433 ,
         1.00592071, -0.43999756]])

In [ ]:
y_train

array([2, 2, 0, 1, 1, 0, 2, 1, 2, 2, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 2, 1,
       2, 1, 2, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1, 0, 2, 0, 2, 2,
       1, 2, 1, 1, 2, 0, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 1, 0, 2, 1, 1, 1,
       2, 0, 2, 0, 2, 0, 1, 1, 1, 2, 0, 2, 1, 1, 2, 0, 2, 2, 0, 0, 2, 1,
       2, 1, 0, 2, 1, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 1, 1,
       2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1,
       1, 1, 0, 1, 2, 0, 2, 2, 1, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 1, 1, 0,
       1, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 0,
       0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 1, 2, 2,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 0, 2, 0, 2, 2, 1, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 0, 0,
       2, 2, 0, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 1,
       2, 1, 0, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 0, 2, 0, 2, 2, 2, 1, 1, 0,
       2, 1, 0, 2, 1, 2, 2, 1, 0, 0, 0, 0, 0, 2, 1,

In [ ]:
y_test

array([0, 1, 1, 2, 2, 1, 1, 0, 1, 2, 1, 2, 0, 2, 1, 1, 0, 2, 2, 2, 1, 2,
       0, 2, 2, 2, 1, 0, 1, 1, 2, 0, 0, 2, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2,
       0, 1, 0, 0, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1,
       2, 2, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 1, 2, 2, 2, 0, 0, 2, 2, 2, 1,
       2, 0, 1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 0,
       0, 2, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 0, 2, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 2, 2, 2, 2, 1,
       2, 1, 1, 0, 1, 0, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 1,
       2, 2, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0,
       2, 2, 2, 2, 0, 0, 2, 1, 2, 2, 2, 2, 0, 0])

In [ ]:
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 1, 2, 2, 1, 1, 0, 1, 2, 1, 2, 0, 2, 1, 1, 0, 2, 2, 2, 1, 2,
       0, 2, 2, 2, 1, 0, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2,
       0, 1, 0, 0, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 0, 0, 0, 1,
       2, 2, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 1, 2, 0, 2, 0, 0, 2, 2, 0, 1,
       2, 0, 1, 1, 0, 2, 1, 2, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 0,
       0, 2, 2, 1, 0, 0, 2, 1, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 2, 1,
       2, 1, 1, 0, 1, 0, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1, 0, 0, 1, 1, 0, 1,
       2, 2, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 0, 1, 0, 1, 1, 0,
       2, 2, 0, 2, 0, 0, 2, 1, 2, 0, 2, 2, 0, 0])

In [ ]:
classifier.predict_proba(x_test)

array([[9.78067231e-001, 1.01710703e-002, 1.17616985e-002],
       [7.69517287e-092, 1.00000000e+000, 7.95953067e-066],
       [2.37241115e-096, 1.00000000e+000, 3.64395987e-071],
       [2.87247306e-044, 4.14371385e-001, 5.85628615e-001],
       [2.81939300e-046, 8.63042398e-004, 9.99136958e-001],
       [8.23698047e-045, 1.00000000e+000, 2.79904929e-039],
       [2.77554021e-187, 1.00000000e+000, 8.28757519e-105],
       [9.88918845e-001, 1.08461612e-002, 2.34994178e-004],
       [1.44234300e-095, 1.00000000e+000, 5.19414674e-072],
       [3.97016375e-001, 8.68880648e-003, 5.94294819e-001],
       [2.62271333e-247, 1.00000000e+000, 1.75563459e-168],
       [3.42214575e-001, 1.03081232e-003, 6.56754613e-001],
       [6.67774156e-001, 3.16683933e-003, 3.29059004e-001],
       [3.42214575e-001, 1.03081232e-003, 6.56754613e-001],
       [1.10837537e-043, 1.00000000e+000, 5.94936016e-049],
       [2.77554021e-187, 1.00000000e+000, 8.28757519e-105],
       [9.96953938e-001, 2.69188452e-003

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[48  0  0]
 [ 4 74  0]
 [ 8  0 78]]


## Menampilkan Tingkat Akurasi

In [ ]:
akurasi = classification_report(y_test, y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.80      1.00      0.89        48
           1       1.00      0.95      0.97        78
           2       1.00      0.91      0.95        86

    accuracy                           0.94       212
   macro avg       0.93      0.95      0.94       212
weighted avg       0.95      0.94      0.95       212



In [ ]:
akurasi = accuracy_score(y_test, y_pred)
print("Tingkat Akurasi : %d persen"%(akurasi*100))

Tingkat Akurasi : 94 persen


In [ ]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)
ydata

y_test  y_pred
0         0       0
1         1       1
2         1       1
3         2       2
4         2       2
..      ...     ...
207       2       0
208       2       2
209       2       2
210       0       0
211       0       0

[212 rows x 2 columns]